### ISSUE TITLE
ModuleNotFoundError: No module named 'araucanaxai'

### ISSUE THREAD

**Issue by ripankundu** [bmi-labmedinfo/araucana-xai#6]
Downloading sklearn-0.0.post1.tar.gz (3.6 kB)
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> See above for output.
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  Preparing metadata (setup.py) ... error
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

While I am trying to install the package using the following command
!pip3 install araucanaxai

It show the error. Could you please solve it or help me how can I solve this installation issues

**Comment by detsutut** [comment]
Hi @ripankundu,

I cannot reproduce your issue, but it might be related to #7 
Please check if the problem persists also in araucanaxai v 0.9.4
