### ISSUE TITLE
Categorical Feature Support

### ISSUE THREAD

**Issue by KuzonFyre** [bmi-labmedinfo/araucana-xai#9]
So I am using a Gradient Boosted Model with this library. It has categorical features as well as numerical features in the dataset. I am able to get a tree for an instance however the categorical features are showing up as numerical. I looked into this and because the tree classifier is from Sci-kit learn it does not support categorical features. I have attempted to modify the araucana-xai code to use CatBoost which supports categorical features but because the neighborhood data brings together similar results, the data I end up trying to train the CatBoost model on only has one label instead of two. Is there any plans to support categorical features in this library?

**Comment by detsutut** [comment]
Hi, Araucana already supports categorical features. Can you provide a minimal, reproducible example?

**Comment by detsutut** [comment]
Closing inactive issue
